name: WF4_Cron Scheduled 

on: 
  schedule:
    - cron: "* * * * *"

jobs:
  job1-on-ubuntu:
    # name: Run on ubuntu-latest
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Ran GA on Cron Schedule"


# Postman request to trigger this Github action on 'repository_dispatch'
# curl --location --request POST 'https://api.github.com/repos/arunmanglick-code/gitactionA/dispatches?accept=application/vnd.github+json' \
# --header 'Authorization: Basic OmdocF9qeW9wZlZ6REh1RmFXR2ljQnJubVE0eHdCWTZlUHozYWxiV1U=' \
# --header 'Content-Type: application/json' \
# --data-raw '{
#   "event_type":"build"
# }'