name: WF3_Over_Pull_Request 

on: 
  schedule:
    - cron: "0/5 * * * *"
    - cron: "0/6 * * * *" 
  pull_request:
    types : [opened, closed, assigned, reopened]

jobs:
  job1-on-ubuntu:
    # name: Run on ubuntu-latest
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Ran GA on Pull Request"
      